// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_xaz6li05pbN32mzH2JHksizwM6Nlybk',
    appId: '1:837453922513:android:028f2186373bb0a76805f0',
    messagingSenderId: '837453922513',
    projectId: 'descubrenarino-945e6',
    storageBucket: 'descubrenarino-945e6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu6JpazXy-x45Nkiwh8f8KPsYxRT8FhoI',
    appId: '1:837453922513:web:d5fd5dce152952546805f0',
    messagingSenderId: '837453922513',
    projectId: 'descubrenarino-945e6',
    authDomain: 'descubrenarino-945e6.firebaseapp.com',
    storageBucket: 'descubrenarino-945e6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvuc4mW1AdV9-wQ2TMp8NOqJt2ZP3XoZ4',
    appId: '1:837453922513:ios:b360381556d1fbc36805f0',
    messagingSenderId: '837453922513',
    projectId: 'descubrenarino-945e6',
    storageBucket: 'descubrenarino-945e6.firebasestorage.app',
    iosBundleId: 'com.example.descubreNarino',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvuc4mW1AdV9-wQ2TMp8NOqJt2ZP3XoZ4',
    appId: '1:837453922513:ios:b360381556d1fbc36805f0',
    messagingSenderId: '837453922513',
    projectId: 'descubrenarino-945e6',
    storageBucket: 'descubrenarino-945e6.firebasestorage.app',
    iosBundleId: 'com.example.descubreNarino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6JpazXy-x45Nkiwh8f8KPsYxRT8FhoI',
    appId: '1:837453922513:web:cfa1ddf255a790056805f0',
    messagingSenderId: '837453922513',
    projectId: 'descubrenarino-945e6',
    authDomain: 'descubrenarino-945e6.firebaseapp.com',
    storageBucket: 'descubrenarino-945e6.firebasestorage.app',
  );

}